# Generated by Django 3.0.7 on 2020-06-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stockdatebase',
            new_name='Stockdatabase',
        ),
    ]
